<?php  //[STAMP] 3f47fe376f3cf6314fc880cf25c58863
// phpcs:ignoreFile
namespace App\Tests\Support\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
