<?php  //[STAMP] 5816cd8acff3e3631f334e501ea545f9
// phpcs:ignoreFile
namespace App\Tests\Support\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
